# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
